# this file uses prebuilt image in dockerhub
services:
  jekyll:
    container_name: website_builder
    image: amirpourmand/al-folio:v0.16.3
    ports:
      #- 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=production
